# Generated by Django 3.2.16 on 2024-09-16 15:09

from django.db import migrations, models
import product.validators


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=8, validators=[product.validators.poz_price], verbose_name='Цена'),
        ),
    ]
